### ISSUE TITLE
Unable to get this working/No Display on OLED?

### ISSUE THREAD

**Issue by AP2K94** [terenceang/SDisk2#12]
hi, i built one of these for a IIe but all I am getting is the led light turn on but no display on the oled , the touch keys light up and that's all? 

Main parts are from aliexpress like;
MH-SD CARD MODULE ( for U3) all pins match pcb and has the 3.3 volt converter onboard (looks to be a clone of LC Studio)
.96" OLED I2C with oval mounting holes (no markings) but Pins match vcc gnd scl sda?
 
Using a 27mhz crystal with 20pf caps (as recommended in its datasheet)

Used minipro tl866 II to write the .hex file from here (no mods) with the fuses set
LFUSE = 0xF7
HFUSE = 0xF9
EFUSE = 0xFF
LOCK BIT=0xFF

I did notice some comments that the pcb was incorrect in particular the pins for the oled can someone please clarify?

thanks

**Comment by mamejay** [comment]
I made a board up using the provided schematic but the 3.3V was everywhere when it should only have been to the SDcard reader.
I got strange behaviour.  Had to do a bunch on bodge wires and finally got it going.  Also , recompiled the firmware to use tactile buttons pulled to ground.

**Comment by AP2K94** [comment]
thanks for the info, will check the voltages but I am thinking its the sd card module causing issues (photo attached) these are not the best and looks like most need modifications using 3 small signal diodes such as 1N4148 and traces cut? alternatively any recommendations on a working module compatible with this project would be great.

Also still not sure why the screen is not displaying? Checked the voltages all good I thought it would at least power up?


 ![sdcard1](https://github.com/terenceang/SDisk2/assets/69714172/aff848f1-4e8a-44c5-be0f-f3457c8f20cd)

**Comment by mamejay** [comment]
What voltage are you getting at the oled?  I had to change mine to 5v as I got no display

**Comment by AP2K94** [comment]
Getting 3.7v at oled vcc?
the oled I have is a generic one (no volt regulator on back) but it does state 3v-5v by the seller so I guess I can try 5v to test?
btw from what location on the pcb do I tap the 5v from?

**Comment by mamejay** [comment]
I created my own PCB using SMD components.  I had to cut all traces coming from the voltage regulator and then add wires from the 5V coming from the IDC connector.

**Comment by Silicon-Surfer** [comment]
The problem is that the ATMEGA328P won't run at such a high frequency on 3.3v. If you look at the datasheet, the max frequency at 3.3v is just over 12mHz. At 27mHz it's being overclocked, so it needs 5v to run.

The quick solution is to cut the traces where 3.3v from the SDCard board is fed to VCC and connect 5v instead.

I've been running mine with this bodge for a year or more and it's been flawless.

![image](https://github.com/terenceang/SDisk2/assets/125940018/d5006564-dffc-4ba2-a100-89f4ee367c56)

**Comment by Silicon-Surfer** [comment]
> thanks for the info, will check the voltages but I am thinking its the sd card module causing issues (photo attached) these are not the best and looks like most need modifications using 3 small signal diodes such as 1N4148 and traces cut? alternatively any recommendations on a working module compatible with this project would be great.
> 
> Also still not sure why the screen is not displaying? Checked the voltages all good I thought it would at least power up?
> 
> ![sdcard1](https://private-user-images.githubusercontent.com/69714172/329819427-aff848f1-4e8a-44c5-be0f-f3457c8f20cd.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTk2MDEsIm5iZiI6MTcxNTU1OTMwMSwicGF0aCI6Ii82OTcxNDE3Mi8zMjk4MTk0MjctYWZmODQ4ZjEtNGU4YS00NGM1LWJlMGYtZjM0NTdjOGYyMGNkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwMDE1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjYyNzZmMThkODhjZWRlYTE2ODEwZDZkY2QwMjk5ZDAwODI0YjZiOGUyMzAzMDEzNjQ3NzcxMDFlMWZhOWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3FcQ-aZ674p2JixSfM1SL89HjxNQHZWHx46y66cqRIw)

Which side of the board are you mounting the SDCard module to? With the connector like your picture, that will have to be on the top of the board (Button/OLED side) to have the correct pin locations. Note where Pin 1 (square pad) is on the connector and where it is on your SDCard module.

**Comment by AP2K94** [comment]
Hi Silicone Surfer,  just to clarify where you have written connect for the 5v line do you just scrape some top layer coating off and solder?

I have another (microSDcard) module on order but will check wiring, thanks for your help.

**Comment by Silicon-Surfer** [comment]
> Hi Silicone Surfer, just to clarify where you have written connect for the 5v line do you just scrape some top layer coating off and solder?
> 
> I have another (microSDcard) module on order but will check wiring, thanks for your help.

Yes, just expose some of the copper layer and use a blob of solder to make the connection. Just make sure that the 3.3v tracks are cut. What this does is disconnects the 3.3v output from the regulator on the SDCard module and uses the 5v supplied by the Apple II instead. I'm guessing that like mine, your problem isn't the card module or OLED display, but the processor isn't working with 3.3v.

Another issue that I had, was that most of the OLED displays on the market have a different pinout to the board. So I had to use wires rather than pins to switch a couple of them around.

**Comment by AP2K94** [comment]
hi just a quick update finally got the new microsd card module , wired it up and it sprang to life! Just need to get the basic push button switches wired up so was going to use vcc and i/o hope that’s correct?
thanks

**Comment by AP2K94** [comment]
all done thanks for all the help greatly appreciated:-)

**Comment by steswart** [comment]
> hi just a quick update finally got the new microsd card module , wired it up and it sprang to life! Just need to get the basic push button switches wired up so was going to use vcc and i/o hope that’s correct? thanks

I am getting the same issue, no OLED display. What SD card module di you use in the end?
