### ISSUE TITLE
Unable to save file. 

### ISSUE THREAD

**Issue by terenceang** [terenceang/SDisk2#2]
Load a new DOS3.3. nic, save a file to it and the file is not there when you do a catalog command.

**Comment by terenceang** [comment]
fixed after replacing xtal with 27mhza.

**Comment by StormTrooper** [comment]
Im having this same issue but already have a 27Mhz fuse in place. Saving to disk goes through all the actions but a catalog doesn't show the file .

**Comment by Silicon-Surfer** [comment]
> Im having this same issue but already have a 27Mhz fuse in place. Saving to disk goes through all the actions but a catalog doesn't show the file .

I had a different issue, when a game tried to write a save file, it seemed to keep repeating the process and by the time I reset the machine, I had a dozen or more copies of the save file. Increasing the card delay setting seems to have fixed the issue, so if you haven't played around with that setting, give that a try as your problem might be card speed related too.
