### ISSUE TITLE
Tactile switches question - Can I just wire them to active high

### ISSUE THREAD

**Issue by mamejay** [terenceang/SDisk2#6]
Hello there,
I am wanting to make a version of this using SMD components as much as possible.
I read through your firmware notes and you mention tactile switches.
Can I just wire them up to VCC and keep them active high similar to you design?  Do you see this as being a problem at all?

Thanks

**Comment by JPT77** [comment]
My exact question. Did you find a solution yet?

**Comment by mamejay** [comment]
Did not get an answer.  I have PCB's and all parts and just need to assemble a board and test.  Hoping to get this done in the next week or so and see what happens with the buttons.

**Comment by Silicon-Surfer** [comment]
The touch switches are configurable but by default they pull the output high, and they work in this circuit that way. So you can just replace them with mechanical switches connected to VCC.

**Comment by mamejay** [comment]
Oh.  I have my switches pulled connected to ground.  I am sure I read you can recompile the code to work with switches being pulled low to enable.

**Comment by JPT77** [comment]
Cool. Silicon-Surfer could you please share your board through github? When you are sure it works...
I do not want to reinvent the wheel another time ;)

mamejay:
Yeah, my guess was to wire the switches to ground too, because you can enable the 20k pullups in the atmega if they aren't already. Do you need to put another resistor between switch and ground? (Sorry, I am a total newbie)

Just don't understand the code, though. I am a total C illiterate ;)

**Comment by mamejay** [comment]
> Cool. Silicon-Surfer could you please share your board through github? When you are sure it works... I do not want to reinvent the wheel another time ;)
> 
> mamejay: Yeah, my guess was to wire the switches to ground too, because you can enable the 20k pullups in the atmega if they aren't already. Do you need to put another resistor between switch and ground? (Sorry, I am a total newbie)
> 
> Just don't understand the code, though. I am a total C illiterate ;)

@JPT77 I have forked this repo and uploaded my Eagle schematic and PCB.  Also have updated hex file, compiled to work with the tactile switches.
